### ISSUE TITLE
exceptions.ValueError: reading beyond the length of the packet

### ISSUE THREAD

**Issue by SSPkrolik** [hybridlogic/txMySQL#4]
I've got the next traceback trying to fetch value with a simple query:

```
{'length': 308,
 'tot_length': 65,
 'w': <txmysql.protocol.MySQLProtocol instance at 0x167ce18>}
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 388, in errback
    self._startRunCallbacks(fail)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 455, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 542, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1076, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1018, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 350, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/krolik/Aptana Studio 3 Workspace/crmchat/src/bin/yachat/txmysql/client.py", line 398, in _doQuery
    result = yield self.client.fetchall(_escape(query, query_args))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1018, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 350, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/krolik/Aptana Studio 3 Workspace/crmchat/src/bin/yachat/txmysql/protocol.py", line 369, in fetchall
    all_rows = yield self._do_fetch(result, types)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1018, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 350, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/krolik/Aptana Studio 3 Workspace/crmchat/src/bin/yachat/txmysql/protocol.py", line 378, in _do_fetch
    rows, more_rows = yield self._fetch(result['stmt_id'], 2, types)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1018, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 350, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/krolik/Aptana Studio 3 Workspace/crmchat/src/bin/yachat/txmysql/protocol.py", line 316, in _fetch
    result = yield self.read_result(data_types=types)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1018, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 350, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/krolik/Aptana Studio 3 Workspace/crmchat/src/bin/yachat/txmysql/protocol.py", line 179, in read_result
    cols.append((yield t.read_lcs()))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1020, in _inlineCallbacks
    result = g.send(result)
  File "/home/krolik/Aptana Studio 3 Workspace/crmchat/src/bin/yachat/txmysql/util.py", line 75, in read_lcs
    defer.returnValue((yield self.read(length)))
  File "/home/krolik/Aptana Studio 3 Workspace/crmchat/src/bin/yachat/txmysql/util.py", line 42, in read
    self._check_length()
  File "/home/krolik/Aptana Studio 3 Workspace/crmchat/src/bin/yachat/txmysql/util.py", line 36, in _check_length
    raise ValueError('reading beyond the length of the packet')
exceptions.ValueError: reading beyond the length of the packet
```

Here's the table:

/\* Creating table for storing conversations */
CREATE TABLE IF NOT EXISTS support_chat_conversations (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    hashid CHAR(32) NOT NULL,
    datetime_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    support_user_id INT NOT NULL,
    customer_id INT,
    message TEXT NOT NULL,
    message_type ENUM('incoming','outgoing','comment','system','result','xaction') default NULL,

```
INDEX USING BTREE(hashid),
INDEX USING BTREE(datetime_created),
INDEX USING BTREE(support_user_id),
INDEX USING BTREE(customer_id),
INDEX USING BTREE(message_type)
```

) ENGINE=MyISAM;

Here's the query:

SELECT \* FROM support_chat_conversations WHERE hashid="%s" % (hashid)

Everything works fine if I remove message_type column from table (suppose the problem is in enum type)

**Comment by SSPkrolik** [comment]
I forgot to mention that I use txMySQL in Tornado
using tornado.platform.twisted integration tool

**Comment by lukemarsden** [comment]
Thanks for the bug report and sorry it took me so long to get back to you - GitHub didn't notify me in any meaningful way. Indeed this is a lack of enum type support in txMySQL - I would welcome a patch for it - https://github.com/hybridlogic/txMySQL/blob/master/txmysql/protocol.py and http://forge.mysql.com/wiki/MySQL_Internals_ClientServer_Protocol should be enough to get started. Thanks!
